CREATE DATABASE scoala_auto;

USE scoala_auto;

CREATE TABLE MASINA (
    MASINA_ID INT PRIMARY KEY,
    MARCA VARCHAR(64) NOT NULL,
    MODELUL VARCHAR(64) NOT NULL,
    ANUL INT NOT NULL,
    CUTIE CHAR(1) NOT NULL CHECK (CUTIE IN ('M', 'A')),
    STARE VARCHAR(16) NOT NULL DEFAULT 'Activ'
);

CREATE TABLE FUNCTIE (
    FUNCTIE_ID INT PRIMARY KEY,
    DENUMIRE_FUNCTIE VARCHAR(64) NOT NULL
);

CREATE TABLE INSTRUCTOR (
    ID_INSTRUCTOR INT PRIMARY KEY,
    NUME VARCHAR(32) NOT NULL,
    PRENUME VARCHAR(32) NOT NULL,
    NUMAR_TELEFON VARCHAR(16) NOT NULL,
    MASINA_ID INT NOT NULL,
    FUNCTIE_ID INT NOT NULL,
    FOREIGN KEY (MASINA_ID) REFERENCES MASINA(MASINA_ID),
    FOREIGN KEY (FUNCTIE_ID) REFERENCES FUNCTIE(FUNCTIE_ID)
);

CREATE TABLE CATEGORIE (
    CATEGORIE_ID CHAR(1) PRIMARY KEY,
    DENUMIRE_CATEGORIE VARCHAR(128) NOT NULL
);

CREATE TABLE STUDENT (
    STUDENT_ID INT PRIMARY KEY, 
    NUME VARCHAR(32) NOT NULL,
    PRENUME VARCHAR(32) NOT NULL,
    IDNP VARCHAR(16) NOT NULL,
    DATA_NASTEREI DATE NOT NULL,
    SEXUL_ID CHAR(1) NOT NULL,
    CATEGORIE_ID CHAR(1) NOT NULL,
    NUMAR_TELEFON VARCHAR(16) NOT NULL,
    INSTRUCTOR_ID INT NOT NULL,
    FOREIGN KEY (CATEGORIE_ID) REFERENCES CATEGORIE(CATEGORIE_ID),
    FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR(ID_INSTRUCTOR)
);

CREATE TABLE SEXIUNI (
    SEXUL_ID CHAR(1) PRIMARY KEY,
    DESCRIERE VARCHAR(16) NOT NULL
);

CREATE TABLE ANGAJAT (
    ANGAJAT_ID INT PRIMARY KEY,    
    NUME VARCHAR(32) NOT NULL,
    PRENUME VARCHAR(32) NOT NULL,
    IDNP VARCHAR(32) NOT NULL,
    DATA_NASTEREI DATE NOT NULL,
    SEXUL_ID CHAR(1) NOT NULL,
    NUMAR_TELEFON VARCHAR(16) NOT NULL,
    FUNCTIE_ID INT NOT NULL,
    SALARIU DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (SEXUL_ID) REFERENCES SEXIUNI(SEXUL_ID),
    FOREIGN KEY (FUNCTIE_ID) REFERENCES FUNCTIE(FUNCTIE_ID)
);

CREATE TABLE PLATI (
    PLATA_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    SUMA DECIMAL(8, 2) NOT NULL,
    DATA_PLATII DATE NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);

CREATE TABLE TIP_EVALUARE (
    TIP_EVALUARE_ID CHAR(1) PRIMARY KEY,
    DESCRIERE VARCHAR(64) NOT NULL
);

CREATE TABLE EVALUARE (
    EVALUARE_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    ID_INSTRUCTOR INT,
    TIP_EVALUARE_ID CHAR(1) NOT NULL,
    DATA_EVALUARII DATE NOT NULL,
    PUNCTAJ INT NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (ID_INSTRUCTOR) REFERENCES INSTRUCTOR(ID_INSTRUCTOR),
    FOREIGN KEY (TIP_EVALUARE_ID) REFERENCES TIP_EVALUARE(TIP_EVALUARE_ID)
);

CREATE TABLE STATUS_PROGRAMARE (
    STATUS_ID CHAR(1) PRIMARY KEY,
    DESCRIERE VARCHAR(32) NOT NULL
);

CREATE TABLE PROGRAMARI (
    PROGRAMARE_ID INT PRIMARY KEY,
    STUDENT_ID INT NOT NULL,
    ID_INSTRUCTOR INT NOT NULL,
    MASINA_ID INT NOT NULL,
    DATA_PROGRAMARII DATE NOT NULL,
    ORA_PROGRAMARII TIME NOT NULL,
    STATUS_ID CHAR(1) NOT NULL,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID),
    FOREIGN KEY (ID_INSTRUCTOR) REFERENCES INSTRUCTOR(ID_INSTRUCTOR),
    FOREIGN KEY (MASINA_ID) REFERENCES MASINA(MASINA_ID),
    FOREIGN KEY (STATUS_ID) REFERENCES STATUS_PROGRAMARE(STATUS_ID)
);

CREATE TABLE INTRETINERE (
    INTRETINERE_ID INT PRIMARY KEY,
    MASINA_ID INT NOT NULL,
    DESCRIERE VARCHAR(256) NOT NULL,
    COST DECIMAL(10, 2) NOT NULL,
    DATA_REPARATIEI DATE NOT NULL,
    FOREIGN KEY (MASINA_ID) REFERENCES MASINA(MASINA_ID)
);
